# Generated by Django 3.0 on 2019-12-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='biography',
            field=models.TextField(default=''),
        ),
    ]
